### ISSUE TITLE
fail to build jkq-ddsim

### ISSUE THREAD

**Issue by Roger-luo** [Roger-luo/quantum-benchmarks#17]
Hi @hillmich

currently our benchmark machine fails to build jkq-ddsim due to the following error:

```sh
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  apps/CMakeLists.txt:3 (find_package)


CMake Error at /usr/share/cmake-3.10/Modules/FindBoost.cmake:1947 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  apps/CMakeLists.txt:3 (find_package)
```

I'm wondering if you have boost installation setup in your cmake? since I don't think we would like to have boost as the default global benchmark environment since it's a quite large dependency. I'm wondering if not, would you mind update the `setup.sh` to install boost for jkq-ddsim?

NOTE: also you might already notice we refactor the benchmark recently to make it more modular.

**Comment by hillmich** [comment]
Thanks for the notification. The simulator does not require the whole of Boost, only the [*program_options*](https://www.boost.org/doc/libs/1_73_0/doc/html/program_options.html) library. 

Do you think just having this particular library in the global env is okay? For example, the [Ubuntu package](https://packages.ubuntu.com/bionic/libboost-program-options-dev) is quite small with about 10KB size.
